name: Qodana
on:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@latest
        with:
          args: --no-build --baseline <qodana.sarif.json>
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_179119923 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'